CREATE TABLE ADDRESSES
   (
      ID BIGINT ,
      ZIPCODE VARCHAR(6) ,
      CITY VARCHAR(20) ,
      STREET VARCHAR(20) NOT NULL ,
      HOUSE VARCHAR(4) NOT NULL ,
      FLAT VARCHAR(3) ,

      CONSTRAINT ADDRESSES_PK Primary Key (ID) ,

      CONSTRAINT ADDRESSES_NATUR_KEY UNIQUE (CITY, STREET, HOUSE, FLAT)
)