CREATE VIEW ALLCONTACTVIEW
  
    AS 
    (

        SELECT 
        FIRSTNAME, LASTNAME, BIRTHDAY, GROUPS, 
        ZIPCODE, CITY, STREET, HOUSE, FLAT, 
        EMAILL, 
        HOMEPHONE.COUNTRYCODE AS HOMEPHONE_COUNTRYCODE, 
        HOMEPHONE.CITYCODE AS HOMEPHONE_CITYCODE, 
        HOMEPHONE.NUMB AS HOMEPHONE_NUMB, 
        HOMEPHONE.PHONETYPE AS HOMEPHONE_PHONETYPE,
        WORKPHONE.COUNTRYCODE AS WORKPHONE_COUNTRYCODE, 
        WORKPHONE.CITYCODE AS WORKPHONE_CITYCODE, 
        WORKPHONE.NUMB AS WORKPHONE_NUMB, 
        WORKPHONE.PHONETYPE AS WORKPHONE_PHONETYPE,

        APP.MOBILEPHONES.COUNTRYCODE AS MOBILEPHONE_COUNTRYCODE, PROVIDERCODE, APP.MOBILEPHONES.NUMB AS MOBILEPHONE_NUMB
        
        FROM   (((((APP.CONTACTS JOIN APP.PERSONS ON APP.CONTACTS.PERSONID = APP.PERSONS.ID)
                JOIN APP.ADDRESSES ON APP.CONTACTS.ADDRESSID = APP.ADDRESSES.ID)
                    JOIN APP.PHONES AS HOMEPHONE ON APP.CONTACTS.HOMEPHONEID = HOMEPHONE.ID) 
                        JOIN APP.PHONES AS WORKPHONE ON APP.CONTACTS.WORKPHONEID = WORKPHONE.ID)     
                            JOIN APP.MOBILEPHONES ON APP.CONTACTS.ID = APP.MOBILEPHONES.CONTACTID)

    )    


