CREATE TABLE CONTACTS
   (
      ID BIGINT ,
      PERSONID BIGINT  NOT NULL ,
      ADDRESSID BIGINT  ,
      EMAILL VARCHAR(20) ,
      HOMEPHONEID BIGINT  ,
      WORKPHONEID BIGINT  ,


      CONSTRAINT CONTACTS_PK Primary Key (ID) ,

      CONSTRAINT PERSONS_FK Foreign Key (PERSONID) REFERENCES PERSONS (ID) ,
      CONSTRAINT ADDRESSES_FK Foreign Key (ADDRESSID) REFERENCES ADDRESSES (ID) ,
      CONSTRAINT HOMEPHONES_FK Foreign Key (HOMEPHONEID) REFERENCES PHONES (ID) ,
      CONSTRAINT WORKPHONES_FK Foreign Key (WORKPHONEID) REFERENCES PHONES (ID) ,

      CONSTRAINT CONTACTS_NATUR_KEY UNIQUE (EMAILL) 
      
    )