CREATE TABLE MOBILEPHONES
   (
      ID BIGINT ,
      COUNTRYCODE VARCHAR(3) ,
      PROVIDERCODE VARCHAR(3) NOT NULL ,
      NUMB VARCHAR(7) NOT NULL ,
      CONTACTID BIGINT  ,

      CONSTRAINT MOBILEPHONES_PK Primary Key (ID) ,

      CONSTRAINT CONTACTS_FK Foreign Key (CONTACTID) REFERENCES CONTACTS (ID) ,

      CONSTRAINT MOBILEPHONES_NATUR_KEY UNIQUE (PROVIDERCODE, NUMB)
    )
