CREATE TABLE PERSONS(
      ID BIGINT ,
      FIRSTNAME VARCHAR(20) ,
      LASTNAME VARCHAR(20) ,
      BIRTHDAY VARCHAR(30) ,
      GROUPS VARCHAR(10)  CHECK ( GROUPS IN ('FAMILY' ,'FRIENDS' ,'WORK')) ,

      CONSTRAINT PERSONS_PK Primary Key (ID) ,

      CONSTRAINT PERSONS_NATUR_KEY UNIQUE (FIRSTNAME, LASTNAME, BIRTHDAY) 

)