CREATE TABLE PHONES
   (
      ID BIGINT ,
      COUNTRYCODE VARCHAR(3) ,
      CITYCODE VARCHAR(3) ,
      NUMB VARCHAR(7) NOT NULL ,
      PHONETYPE VARCHAR(10) CHECK (PHONETYPE IN('UNKNOWN','HOMEPHONE','WORKPHONE')) ,
      
      CONSTRAINT PHONES_PK Primary Key (ID) ,

      CONSTRAINT PHONES_NATUR_KEY UNIQUE (CITYCODE, NUMB) 
    )   