/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  roma
 * Created: 23.08.2016
 */
AUTOCOMMIT OFF;

CREATE TABLE PERSONS
   (
      ID INTEGER  NOT NULL ,
      FIRSTNAME VARCHAR(20) NOT NULL ,
      LASTNAME VARCHAR(20) NOT NULL ,
      BIRTHDAY VARCHAR(10) NOT NULL ,
      GROUPID  INTEGER  NOT NULL 
    );

ALTER TABLE PERSONS
   ADD CONSTRAINT PERSONS_PK Primary Key (
      ID);
ALTER TABLE PERSONS
   ADD CONSTRAINT GROUPS_FK Foreign Key (
      GROUPID)
   REFERENCES GROUPS (
      ID);



CREATE TABLE GROUPS
   {
       ID INTEGER NOT NULL ,
       TITLE VARCHAR(10) NOT NULL , 
   };
ALTER TABLE GROUPS
   ADD CONSTRAINT GROUPS_PK Primary Key (
      ID);



CREATE TABLE ADDRESSES
   (
      ID INTEGER  NOT NULL,
      ZIPCODE VARCHAR(6) NOT NULL ,
      CITY VARCHAR(20) NOT NULL ,
      STREET VARCHAR(20) NOT NULL ,
      HOUSE VARCHAR(4) NOT NULL ,
      FLAT VARCHAR(3) NOT NULL 
    );

ALTER TABLE ADDRESSES
   ADD CONSTRAINT ADDRESSES_PK Primary Key (
      ID);


CREATE TABLE PHONES
   (
      ID INTEGER  NOT NULL ,
      COUNTRYCODE VARCHAR(3) NOT NULL ,
      CITYCODE VARCHAR(3) NOT NULL ,
      NUMB VARCHAR(7) NOT NULL ,
      PHONETYPEID INTEGER NOT NULL
    );

ALTER TABLE PHONES
   ADD CONSTRAINT PHONES_PK Primary Key (
      ID);
ALTER TABLE PHONES
   ADD CONSTRAINT PHONETYPES_FK Foreign Key (
      PHONETYPEID)
   REFERENCES PHONETYPES (
      ID);


CREATE TABLE PHONETYPES
{
    ID INTEGER NOT NULL ,
    TITLE VARCHAR(10) NOT NULL
};
ALTER TABLE PHONETYPES
   ADD CONSTRAINT PHONETYPES_PK Primary Key (
      ID);

CREATE TABLE MOBILEPHONES
   (
      ID INTEGER  NOT NULL,
      COUNTRYCODE VARCHAR(3) NOT NULL ,
      PROVIDERCODE VARCHAR(3) NOT NULL ,
      NUMB VARCHAR(7) NOT NULL ,
      CONTACTID INTEGER NOT NULL
    );

ALTER TABLE MOBILEPHONES
   ADD CONSTRAINT MOBILEPHONES_PK Primary Key (
      ID);
ALTER TABLE MOBILEPHONES
   ADD CONSTRAINT CONTACTS_FK Foreign Key (
      CONTACTID)
   REFERENCES CONTACTS (
      ID);



CREATE TABLE CONTACTS
   {
      ID INTEGER NOT NULL ,
      PERSONID INTEGER NOT NULL ,
      ADDRESSID INTEGER NOT NULL ,
      EMAILL VARCHAR(20) ,
      HOMEPHONEID INTEGER NOT NULL ,
      WORKPHONEID INTEGER NOT NULL ,
      CONTACTBOOKID INTEGER NOT NULL
   };

ALTER TABLE CONTACTS
   ADD CONSTRAINT CONTACTS_PK Primary Key (
      ID);
ALTER TABLE CONTACTS
   ADD CONSTRAINT PERSONS_FK Foreign Key (
      PERSONID)
   REFERENCES PERSONS (
      ID);

ALTER TABLE CONTACTS
   ADD CONSTRAINT ADDRESSES_FK Foreign Key (
      ADDRESSID)
   REFERENCES ADDRESSES (
      ID);

ALTER TABLE CONTACTS
   ADD CONSTRAINT HOMEPHONES_FK Foreign Key (
      HOMEPHONEID)
   REFERENCES PHONES (
      ID);

ALTER TABLE CONTACTS
   ADD CONSTRAINT WORKPHONES_FK Foreign Key (
      WORKPHONEID)
   REFERENCES PHONES (
      ID);


CREATE TABLE CONTACTBOOKS
    {
      ID INTEGER NOT NULL 
    };
ALTER TABLE CONTACTBOOKS
   ADD CONSTRAINT CONTACTBOOKS_PK Primary Key (
      ID);

