 SELECT 
        APP.MOBILEPHONES.COUNTRYCODE AS COUNTRYCODE,
        APP.MOBILEPHONES.PROVIDERCODE AS PROVIDERCODE,
        APP.MOBILEPHONES.NUMB AS NUMB 
  
        FROM ((APP.PERSONS JOIN APP.CONTACTS ON APP.CONTACTS.PERSONID = APP.PERSONS.ID)      
                           JOIN APP.MOBILEPHONES ON APP.CONTACTS.ID = APP.MOBILEPHONES.CONTACTID) 

        WHERE (APP.PERSONS.FIRSTNAME = ? ) AND (APP.PERSONS.LASTNAME = ? ) AND (APP.PERSONS.BIRTHDAY = ? ) 
 

